[2022-07-26 01:52:40,136] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.create_historic_table manual__2022-07-26T01:52:38.961649+00:00 [queued]>
[2022-07-26 01:52:40,159] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: GOOG_historic_data.create_historic_table manual__2022-07-26T01:52:38.961649+00:00 [queued]>
[2022-07-26 01:52:40,160] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 01:52:40,161] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-07-26 01:52:40,162] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-26 01:52:40,194] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): create_historic_table> on 2022-07-26 01:52:38.961649+00:00
[2022-07-26 01:52:40,200] {standard_task_runner.py:52} INFO - Started process 522 to run task
[2022-07-26 01:52:40,205] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'GOOG_historic_data', 'create_historic_table', 'manual__2022-07-26T01:52:38.961649+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/open_options.py', '--cfg-path', '/tmp/tmparjlumjv', '--error-file', '/tmp/tmpsuypofwg']
[2022-07-26 01:52:40,207] {standard_task_runner.py:80} INFO - Job 39: Subtask create_historic_table
[2022-07-26 01:52:40,318] {task_command.py:371} INFO - Running <TaskInstance: GOOG_historic_data.create_historic_table manual__2022-07-26T01:52:38.961649+00:00 [running]> on host 527e7914f635
[2022-07-26 01:52:40,437] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vardhan
AIRFLOW_CTX_DAG_ID=GOOG_historic_data
AIRFLOW_CTX_TASK_ID=create_historic_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-26T01:52:38.961649+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-26T01:52:38.961649+00:00
[2022-07-26 01:52:40,454] {base.py:68} INFO - Using connection ID 'postgres_optionsdata' for task execution.
[2022-07-26 01:52:40,463] {dbapi.py:231} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS historic_GOOG (
            symbol VARCHAR(32) NOT NULL,
            date BIGINT,
            high_price DOUBLE PRECISION,
            low_price DOUBLE PRECISION,
            open_price DOUBLE PRECISION,
            close_price DOUBLE PRECISION,
            total_volume INTEGER,
            PRIMARY KEY (symbol, date)
        )
    , parameters: None
[2022-07-26 01:52:40,474] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/open_options.py", line 44, in create_table_historic_data
    """)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(historic_goog, 2200) already exists.

[2022-07-26 01:52:40,494] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=GOOG_historic_data, task_id=create_historic_table, execution_date=20220726T015238, start_date=20220726T015240, end_date=20220726T015240
[2022-07-26 01:52:40,520] {standard_task_runner.py:97} ERROR - Failed to execute job 39 for task create_historic_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(historic_goog, 2200) already exists.
; 522)
[2022-07-26 01:52:40,548] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-26 01:52:40,656] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
